// Initial realistic dataset for Reviva Phase 1 & Phase 2 Frontend

export const INITIAL_TRANSACTIONS = [
  {
    _id: "txn_001",
    razorpayPaymentId: "pay_N1x89aK7mL2pQ1",
    razorpayOrderId: "order_K91a82b3c4",
    customerName: "Rahul Sharma",
    customerEmail: "rahul.sharma@example.com",
    customerPhone: "+91 98765 43210",
    customerSegment: "Loyal Subscriber (14 mo)",
    amount: 1499,
    currency: "INR",
    status: "failed", // failed, retrying, recovered, action_needed, abandoned
    rawErrorCode: "BAD_REQUEST_PAYMENT_TIMED_OUT",
    rawErrorDescription: "Bank server timeout during authorization",
    category: "BANK_FAILURE", // INSUFFICIENT_FUNDS, CARD_EXPIRED, AUTHENTICATION_FAILURE, BANK_FAILURE, RISK_BLOCK, UNCLASSIFIED
    aiCategoryConfidence: 0.94,
    retryCount: 1,
    maxRetries: 3,
    nextRetryAt: new Date(Date.now() + 3600000).toISOString(), // in 1 hr
    llmRetryReasoning: "Bank server timeouts occur predominantly during peak banking hours (10 AM - 12 PM). A short 1-hour retry window allows the upstream bank gateway to recover while maintaining customer intent.",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    aiMessageVariantA: {
      tone: "Friendly & Empathetic",
      channel: "email",
      subject: "Quick update regarding your Reviva subscription payment",
      body: "Hi Rahul, we noticed your payment of ₹1,499 was interrupted due to a temporary bank timeout. No worries at all! Our system will automatically re-attempt the charge in an hour. Alternatively, click below if you'd like to complete it right now.",
      predictedConversion: 0.78,
    },
    aiMessageVariantB: {
      tone: "Direct & Urgent",
      channel: "email",
      subject: "Action needed: Payment authorization paused",
      body: "Hello Rahul, your payment of ₹1,499 failed due to a bank gateway timeout. To keep your service active without interruption, please update or retry your payment now.",
      predictedConversion: 0.65,
    },
    selectedVariant: "A",
  },
  {
    _id: "txn_002",
    razorpayPaymentId: "pay_M82x01bL3m4pP2",
    razorpayOrderId: "order_L82b93c4d5",
    customerName: "Priya Mehta",
    customerEmail: "priya.m@techcorp.in",
    customerPhone: "+91 98123 45678",
    customerSegment: "Enterprise Plan (8 mo)",
    amount: 4999,
    currency: "INR",
    status: "retrying",
    rawErrorCode: "PAYMENT_INSUFFICIENT_FUNDS",
    rawErrorDescription: "Account balance insufficient to cover transaction",
    category: "INSUFFICIENT_FUNDS",
    aiCategoryConfidence: 0.98,
    retryCount: 2,
    maxRetries: 3,
    nextRetryAt: new Date(Date.now() + 86400000 * 2).toISOString(), // in 2 days
    llmRetryReasoning: "Insufficient funds failures recover best when timed with standard payroll distribution cycles (end of month / 1st of month). Retrying in 48 hours maximizes successful collection without triggering spam blocks.",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    aiMessageVariantA: {
      tone: "Empathetic & Flexible",
      channel: "whatsapp",
      subject: "Friendly reminder from Reviva",
      body: "Hi Priya! Your recent renewal of ₹4,999 could not be completed due to insufficient funds. We've paused retries for 48 hours to give you time. Need to switch to a different payment method? Tap below to update securely.",
      predictedConversion: 0.82,
    },
    aiMessageVariantB: {
      tone: "Incentivized",
      channel: "whatsapp",
      subject: "Update payment & save 5%",
      body: "Hey Priya, payment for ₹4,999 didn't go through. Update your payment method in the next 24 hours to secure your active subscription status!",
      predictedConversion: 0.71,
    },
    selectedVariant: "A",
  },
  {
    _id: "txn_003",
    razorpayPaymentId: "pay_K71c45dE9n2xX3",
    razorpayOrderId: "order_M73c04d5e6",
    customerName: "Amit Kulkarni",
    customerEmail: "amit.k@gmail.com",
    customerPhone: "+91 99887 65432",
    customerSegment: "Basic Plan (3 mo)",
    amount: 2999,
    currency: "INR",
    status: "action_needed",
    rawErrorCode: "CARD_EXPIRED",
    rawErrorDescription: "Card validity period expired 04/25",
    category: "CARD_EXPIRED",
    aiCategoryConfidence: 0.99,
    retryCount: 0,
    maxRetries: 0,
    nextRetryAt: null,
    llmRetryReasoning: "Automatic retries will consistently fail on expired cards. Auto-retry is disabled for this category. Immediate customer outreach with a secure card update link is required.",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    aiMessageVariantA: {
      tone: "Supportive",
      channel: "email",
      subject: "Your payment card on file has expired",
      body: "Hi Amit, it looks like the credit card associated with your ₹2,999 plan has expired. Please take 30 seconds to enter your updated card details so your service remains uninterrupted.",
      predictedConversion: 0.89,
    },
    aiMessageVariantB: {
      tone: "Urgent",
      channel: "email",
      subject: "Urgent: Card expired for payment ₹2,999",
      body: "Hi Amit, your payment failed because your card is expired. Update your billing info now to prevent account suspension.",
      predictedConversion: 0.76,
    },
    selectedVariant: "A",
  },
  {
    _id: "txn_004",
    razorpayPaymentId: "pay_J60d34eF8m1yY4",
    razorpayOrderId: "order_N64d15e6f7",
    customerName: "Sara Joseph",
    customerEmail: "sara.j@designco.com",
    customerPhone: "+91 97654 32109",
    customerSegment: "Pro Plan (18 mo)",
    amount: 899,
    currency: "INR",
    status: "recovered",
    rawErrorCode: "BAD_REQUEST_PAYMENT_OTP_INCORRECT",
    rawErrorDescription: "User entered incorrect OTP during 3D Secure verification",
    category: "AUTHENTICATION_FAILURE",
    aiCategoryConfidence: 0.92,
    retryCount: 1,
    maxRetries: 3,
    nextRetryAt: null,
    llmRetryReasoning: "OTP failures indicate high customer intent but friction during checkout. Sending an instant SMS with a quick 1-click retry link resulted in immediate customer conversion.",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    aiMessageVariantA: {
      tone: "Direct & Helpful",
      channel: "sms",
      subject: "Complete your ₹899 transaction",
      body: "Hi Sara, your OTP verification for ₹899 timed out. Tap here to quickly re-complete your payment: https://reviva.io/pay/pay_J60d34eF8m1yY4",
      predictedConversion: 0.91,
    },
    aiMessageVariantB: {
      tone: "Friendly",
      channel: "sms",
      subject: "Try payment again",
      body: "Hey Sara! Looks like OTP failed. No problem, retry your payment here in one tap: https://reviva.io/pay/pay_J60d34eF8m1yY4",
      predictedConversion: 0.85,
    },
    selectedVariant: "A",
  },
  {
    _id: "txn_005",
    razorpayPaymentId: "pay_H50e23gF7k0zZ5",
    razorpayOrderId: "order_P55e26f7g8",
    customerName: "Vikram Malhotra",
    customerEmail: "vikram.m@investments.in",
    customerPhone: "+91 98450 12345",
    customerSegment: "Premium Plan (5 mo)",
    amount: 12500,
    currency: "INR",
    status: "recovered",
    rawErrorCode: "GATEWAY_ERROR",
    rawErrorDescription: "HDFC Bank processing node unreachable",
    category: "BANK_FAILURE",
    aiCategoryConfidence: 0.96,
    retryCount: 2,
    maxRetries: 3,
    nextRetryAt: null,
    llmRetryReasoning: "Bank node outage resolved after 2 hours. Scheduled automated background retry successfully captured full payment without customer intervention.",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    aiMessageVariantA: {
      tone: "Informative",
      channel: "email",
      subject: "Payment recovered successfully",
      body: "Hi Vikram, your payment of ₹12,500 has been successfully processed following a brief bank gateway recovery. Your invoice is now attached.",
      predictedConversion: 0.95,
    },
    aiMessageVariantB: {
      tone: "Brief",
      channel: "email",
      subject: "Payment successful",
      body: "Hello Vikram, your payment of ₹12,500 was completed successfully. Thank you for your business!",
      predictedConversion: 0.90,
    },
    selectedVariant: "A",
  },
  {
    _id: "txn_006",
    razorpayPaymentId: "pay_G40f12hE6j9aA6",
    razorpayOrderId: "order_Q46f37g8h9",
    customerName: "Ananya Roy",
    customerEmail: "ananya.roy@startup.io",
    customerPhone: "+91 91234 56789",
    customerSegment: "Starter Plan (1 mo)",
    amount: 1999,
    currency: "INR",
    status: "failed",
    rawErrorCode: "RISK_FRAUD_FLAG",
    rawErrorDescription: "High risk fraud score detected by card issuer",
    category: "RISK_BLOCK",
    aiCategoryConfidence: 0.97,
    retryCount: 0,
    maxRetries: 0,
    nextRetryAt: null,
    llmRetryReasoning: "Risk flags require manual merchant review or identity re-verification to prevent chargeback penalties. Auto-retries strictly disabled.",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    aiMessageVariantA: {
      tone: "Secure & Professional",
      channel: "email",
      subject: "Security check required for transaction ₹1,999",
      body: "Hi Ananya, your recent transaction was flagged by security rules. Please contact our support team or verify your billing zip code to proceed.",
      predictedConversion: 0.54,
    },
    aiMessageVariantB: {
      tone: "Direct",
      channel: "email",
      subject: "Payment security notification",
      body: "Hello Ananya, your payment was blocked due to a risk check. Please reach out to support.",
      predictedConversion: 0.48,
    },
    selectedVariant: "A",
  }
];

export const INITIAL_RETRY_RULES = [
  {
    id: "rule_1",
    category: "INSUFFICIENT_FUNDS",
    categoryLabel: "Insufficient Funds",
    retryDelayHours: 72,
    autoRetryEnabled: true,
    maxAttempts: 3,
    description: "Wait 3 days for payroll credit cycles before auto-retrying.",
  },
  {
    id: "rule_2",
    category: "BANK_FAILURE",
    categoryLabel: "Bank Downtime / Server Timeout",
    retryDelayHours: 1,
    autoRetryEnabled: true,
    maxAttempts: 4,
    description: "Retry quickly after 1 hour once gateway nodes recover.",
  },
  {
    id: "rule_3",
    category: "AUTHENTICATION_FAILURE",
    categoryLabel: "OTP / Auth Failure",
    retryDelayHours: 6,
    autoRetryEnabled: true,
    maxAttempts: 2,
    description: "Send instant SMS nudge; retry payment link after 6 hours.",
  },
  {
    id: "rule_4",
    category: "CARD_EXPIRED",
    categoryLabel: "Card Expired",
    retryDelayHours: 0,
    autoRetryEnabled: false,
    maxAttempts: 0,
    description: "No auto-retry. Send email/WhatsApp link to update card details.",
  },
  {
    id: "rule_5",
    category: "RISK_BLOCK",
    categoryLabel: "Risk & Fraud Block",
    retryDelayHours: 0,
    autoRetryEnabled: false,
    maxAttempts: 0,
    description: "No auto-retry. Flag transaction for merchant risk review.",
  }
];

export const INITIAL_SETTINGS = {
  companyName: "Acme Fintech Corp",
  recoveryEmail: "billing@acmefintech.com",
  brandTone: "Friendly & Empathetic", // Friendly & Empathetic, Professional & Direct, Urgent, Conversational
  llmProvider: "Claude 3.5 Sonnet (Recommended)",
  confidenceThreshold: 85,
  channels: {
    email: true,
    sms: true,
    whatsapp: true,
  },
  razorpayWebhookSecret: "whsec_reviva_98123abcdef45678",
  razorpayKeyId: "rzp_live_89123456789abc",
  webhookEndpointUrl: "https://api.reviva.io/v1/webhooks/razorpay",
};
